### ISSUE TITLE
Add description and topics to repo

### ISSUE THREAD

**Issue by aschrijver** [ietf/terminology#11]
The repository has no description text or labels. It will show up in `/stars` list as just "terminology" (therefore I have not starred yet).

Also without topics most people will not find the repo. Some suggestions to add: inclusion, inclusiveness, inclusivity, terminology, diversity, ietf, internet-draft, etc.

Also, shouldn't there be a LICENSE?

**Comment by larseggert** [comment]
I'll add your suggested topics, thanks for those! I'll also see if I can update the description.

In terms of a license, do people think the [TLP](https://trustee.ietf.org/documents/trust-legal-provisions/) should apply here, i.e., should the license be the Revised BSD License?
