### ISSUE TITLE
in-solidarity-bot config

### ISSUE THREAD

**Issue by larseggert** [ietf/terminology#14]
https://github.com/NTAP/isb-ietf-config contains a [configuration file](.github/in-solidarity.yml) for [in-solidarity-bot](https://github.com/jpoehnelt/in-solidarity-bot) that flags the terms in the README of this repo.

Would it make sense to merge that config (and the instructions) here, or is standalone preferred?

**Comment by martinthomson** [comment]
Yes, yes it would make sense.
