### ISSUE TITLE
Profanity

### ISSUE THREAD

**Issue by nitrocode** [ietf/terminology#15]
Here's a list that could be added: https://www.cs.cmu.edu/~biglou/resources/

**Comment by martinthomson** [comment]
Probably a little too broad to strictly enforce in the same way that the existing words might be, but a useful resource for sure.  To take an example, I notice that "australian" is listed, but that is a newspaper of some reknown as well as a word without negative connotations in many contexts.

The list is too long to give each word proper treatment; nor would that be necessary in most cases.  Most of these are not words that have never been used in the sort of discourse this project is aiming to improve.

**Comment by larseggert** [comment]
Given that the IETF has consensus to rely on NISTIR 8366, this seems overtaken by events.
