### ISSUE TITLE
Blind

### ISSUE THREAD

**Issue by martinthomson** [ietf/terminology#17]
This seems pretty clear ableist language in some usage.  I recently removed the word "blind" from a document with no replacement; it was being used alongside a good definition of what was really meant.  That is often more appropriate than finding a replacement.

However, we might need to offer the crypto people a better name for "blind signatures" and "blinding".  "Masking" might be less contentious here, or maybe using the name of the inventor ("Chaum signatures" perhaps).

See #6 and #5.  This word also appears on the list cited by #15.

**Comment by jimfenton** [comment]
Maybe "unattributable"?

I would avoid using the name of an inventor, both because that may be too specific and because there has been a trend in some other contexts to move away from inventor/discoverer's names to more descriptive terms.

**Comment by larseggert** [comment]
I did the easy thing in #25.

If you want to give me a regex and some suggestions for more specific replacements, I will add them.
