### ISSUE TITLE
Awesome resource to link to on avoiding abelist language

### ISSUE THREAD

**Issue by mallory** [ietf/terminology#5]
https://www.autistichoya.com/p/ableist-words-and-terms-to-avoid.html.

It's a link, but also could elaborate some relevant terms in the tabled list, too.

**Comment by nllz** [comment]
I tried to integrate those in this PR: https://github.com/ietf/terminology/pull/6

**Comment by mallory** [comment]
I would like to see a section of the repo where we can keep a bibliography of relevant links like the one from Lydia above, in addition to the implementations in the technical community.

**Comment by larseggert** [comment]
Given that the IETF has consensus to rely on NISTIR 8366, this seems overtaken by events.
